// Generated by tools/build.py from data/projects.json. Don't edit by hand.
window.PP_RING = [
  "bridge-crossing-rl-sim",
  "vixxing",
  "claimtracker",
  "window-works",
  "employee-directory",
  "toy-browser",
  "normalization-sim",
  "christmas-packing-2025",
  "sprite-mapper",
  "dashboard-viewer",
  "convert-image",
  "fruit-classifier"
];
